from __future__ import annotations

from pathlib import Path

import polars

class SpssMetadata:
    @property
    def file_label(self) -> str: ...
    @property
    def file_encoding(self) -> str: ...
    @property
    def compression(self) -> str: ...
    @property
    def creation_time(self) -> str: ...
    @property
    def modification_time(self) -> str: ...
    @property
    def notes(self) -> list[str]: ...
    @property
    def number_rows(self) -> int | None: ...
    @property
    def number_columns(self) -> int: ...
    @property
    def file_format(self) -> str: ...
    @property
    def variable_names(self) -> list[str]: ...
    @property
    def variable_labels(self) -> dict[str, str]: ...
    @property
    def variable_format(self) -> dict[str, str]: ...
    @property
    def arrow_data_types(self) -> dict[str, str]: ...
    @property
    def variable_value_labels(self) -> dict[str, dict[float | str, str]]: ...
    @property
    def variable_alignment(self) -> dict[str, str]: ...
    @property
    def variable_storage_width(self) -> dict[str, int]: ...
    @property
    def variable_display_width(self) -> dict[str, int]: ...
    @property
    def variable_measure(self) -> dict[str, str]: ...
    @property
    def variable_missing_values(self) -> dict[str, list[dict]]: ...
    @property
    def mr_sets(self) -> dict[str, dict]: ...
    @property
    def variable_role(self) -> dict[str, str]: ...
    @property
    def weight_variable(self) -> str | None: ...
    @property
    def schema(self) -> dict: ...

    def label(self, name: str) -> str | None: ...
    def format(self, name: str) -> str | None: ...
    def measure(self, name: str) -> str | None: ...
    def role(self, name: str) -> str | None: ...
    def value(self, name: str) -> dict[float | str, str] | None: ...
    def check_var(self, name: str) -> None: ...
    def summary(self) -> None: ...
    def describe(self, names: str | list[str]) -> None: ...
    def diff(
        self, other: SpssMetadata, print_output: bool = True
    ) -> MetaDiff: ...

class MetaDiff:
    @property
    def is_match(self) -> bool: ...
    @property
    def file_level(self) -> dict: ...
    @property
    def variables_only_in_self(self) -> list[str]: ...
    @property
    def variables_only_in_other(self) -> list[str]: ...
    @property
    def variable_labels(self) -> list[dict]: ...
    @property
    def variable_value_labels(self) -> list[dict]: ...
    @property
    def variable_format(self) -> list[dict]: ...
    @property
    def variable_measure(self) -> list[dict]: ...
    @property
    def variable_display_width(self) -> list[dict]: ...
    @property
    def variable_storage_width(self) -> list[dict]: ...
    @property
    def variable_missing_values(self) -> list[dict]: ...
    @property
    def mr_sets(self) -> list[dict]: ...
    @property
    def variable_role(self) -> list[dict]: ...
    def print_summary(self) -> None: ...

def read_sav(
    path: str,
    *,
    columns: list[int] | list[str] | None = None,
    n_rows: int | None = None,
    row_index_name: str | None = None,
    row_index_offset: int = 0,
) -> tuple[polars.DataFrame, SpssMetadata]: ...
def read_sav_metadata(path: str) -> SpssMetadata: ...
def scan_sav(
    path: str,
    *,
    columns: list[int] | list[str] | None = None,
    n_rows: int | None = None,
    row_index_name: str | None = None,
    row_index_offset: int = 0,
) -> tuple[polars.LazyFrame, SpssMetadata]: ...
def write_sav(
    df: polars.DataFrame,
    path: str | Path,
    *,
    meta: SpssMetadata | None = None,
    compress: bool = True,
    file_label: str | None = None,
    variable_labels: dict[str, str] | None = None,
    variable_value_labels: dict[str, dict] | None = None,
    variable_measure: dict[str, str] | None = None,
    variable_format: dict[str, str] | None = None,
    variable_display_width: dict[str, int] | None = None,
    missing_ranges: dict[str, list] | None = None,
    notes: str | list[str] | None = None,
    weight_variable: str | None = None,
) -> None: ...
