from __future__ import annotations

import polars

class SpssMetadata:
    @property
    def file_label(self) -> str: ...
    @property
    def file_encoding(self) -> str: ...
    @property
    def compression(self) -> str: ...
    @property
    def creation_time(self) -> str: ...
    @property
    def modification_time(self) -> str: ...
    @property
    def notes(self) -> list[str]: ...
    @property
    def number_rows(self) -> int | None: ...
    @property
    def number_columns(self) -> int: ...
    @property
    def file_format(self) -> str: ...
    @property
    def variable_names(self) -> list[str]: ...
    @property
    def variable_labels(self) -> dict[str, str]: ...
    @property
    def spss_variable_types(self) -> dict[str, str]: ...
    @property
    def rust_variable_types(self) -> dict[str, str]: ...
    @property
    def variable_value_labels(self) -> dict[str, dict[float | str, str]]: ...
    @property
    def variable_alignment(self) -> dict[str, str]: ...
    @property
    def variable_storage_width(self) -> dict[str, int]: ...
    @property
    def variable_display_width(self) -> dict[str, int]: ...
    @property
    def variable_measure(self) -> dict[str, str]: ...
    @property
    def variable_missing(self) -> dict[str, list[dict]]: ...
    @property
    def mr_sets(self) -> dict[str, dict]: ...
    @property
    def weight_variable(self) -> str | None: ...
    @property
    def schema(self) -> dict: ...

    def label(self, name: str) -> str | None: ...
    def format(self, name: str) -> str | None: ...
    def measure(self, name: str) -> str | None: ...
    def value(self, name: str) -> dict[float | str, str] | None: ...
    def check_var(self, name: str) -> None: ...
    def summary(self) -> None: ...
    def describe(self, names: str | list[str]) -> None: ...
    def diff(
        self, other: SpssMetadata, print_output: bool = True
    ) -> MetaDiff: ...

class MetaDiff:
    @property
    def is_match(self) -> bool: ...
    @property
    def file_level(self) -> dict: ...
    @property
    def variables_only_in_self(self) -> list[str]: ...
    @property
    def variables_only_in_other(self) -> list[str]: ...
    @property
    def variable_labels(self) -> list[dict]: ...
    @property
    def variable_value_labels(self) -> list[dict]: ...
    @property
    def spss_variable_types(self) -> list[dict]: ...
    @property
    def variable_measure(self) -> list[dict]: ...
    @property
    def variable_display_width(self) -> list[dict]: ...
    @property
    def variable_storage_width(self) -> list[dict]: ...
    @property
    def variable_missing(self) -> list[dict]: ...
    @property
    def mr_sets(self) -> list[dict]: ...
    def print_summary(self) -> None: ...

def read_sav(path: str) -> tuple[polars.DataFrame, SpssMetadata]: ...
def read_sav_metadata(path: str) -> SpssMetadata: ...
def scan_sav(path: str) -> tuple[polars.LazyFrame, SpssMetadata]: ...
