from __future__ import annotations

from pathlib import Path

import polars

class SpssMetadata:
    def __init__(
        self,
        *,
        file_label: str | None = None,
        notes: str | list[str] | None = None,
        weight_variable: str | None = None,
        variable_labels: dict[str, str | None] | None = None,
        variable_value_labels: dict[str, dict[int | float | str, str] | None] | None = None,
        variable_formats: dict[str, str | None] | None = None,
        variable_measures: dict[str, str | None] | None = None,
        variable_display_widths: dict[str, int | None] | None = None,
        variable_alignments: dict[str, str | None] | None = None,
        variable_missing_values: dict[str, dict | None] | None = None,
        variable_roles: dict[str, str | None] | None = None,
        variable_attributes: dict[str, dict[str, list[str]] | None] | None = None,
        mr_sets: dict[str, dict | None] | None = None,
    ) -> None: ...

    # Bulk update (returns new SpssMetadata)
    def update(
        self,
        *,
        file_label: str | None = None,
        notes: str | list[str] | None = None,
        weight_variable: str | None = None,
        variable_labels: dict[str, str | None] | None = None,
        variable_value_labels: dict[str, dict[int | float | str, str] | None] | None = None,
        variable_formats: dict[str, str | None] | None = None,
        variable_measures: dict[str, str | None] | None = None,
        variable_display_widths: dict[str, int | None] | None = None,
        variable_alignments: dict[str, str | None] | None = None,
        variable_missing_values: dict[str, dict | None] | None = None,
        variable_roles: dict[str, str | None] | None = None,
        variable_attributes: dict[str, dict[str, list[str]] | None] | None = None,
        mr_sets: dict[str, dict | None] | None = None,
    ) -> SpssMetadata: ...

    # Chainable single-field setters (each returns new SpssMetadata)
    def with_file_label(self, value: str) -> SpssMetadata: ...
    def with_notes(self, value: str | list[str]) -> SpssMetadata: ...
    def with_weight_variable(self, value: str | None) -> SpssMetadata: ...
    def with_variable_labels(self, value: dict[str, str | None]) -> SpssMetadata: ...
    def with_variable_value_labels(self, value: dict[str, dict[int | float | str, str] | None]) -> SpssMetadata: ...
    def with_variable_formats(self, value: dict[str, str | None]) -> SpssMetadata: ...
    def with_variable_measures(self, value: dict[str, str | None]) -> SpssMetadata: ...
    def with_variable_display_widths(self, value: dict[str, int | None]) -> SpssMetadata: ...
    def with_variable_alignments(self, value: dict[str, str | None]) -> SpssMetadata: ...
    def with_variable_missing_values(self, value: dict[str, dict | None]) -> SpssMetadata: ...
    def with_variable_roles(self, value: dict[str, str | None]) -> SpssMetadata: ...
    def with_variable_attributes(self, value: dict[str, dict[str, list[str]] | None]) -> SpssMetadata: ...
    def with_mr_sets(self, value: dict[str, dict | None]) -> SpssMetadata: ...

    # Properties (read-only)
    @property
    def file_label(self) -> str: ...
    @property
    def file_encoding(self) -> str: ...
    @property
    def compression(self) -> str: ...
    @property
    def creation_time(self) -> str: ...
    @property
    def notes(self) -> list[str]: ...
    @property
    def number_rows(self) -> int | None: ...
    @property
    def number_columns(self) -> int: ...
    @property
    def file_format(self) -> str: ...
    @property
    def variable_names(self) -> list[str]: ...
    @property
    def variable_labels(self) -> dict[str, str]: ...
    @property
    def variable_formats(self) -> dict[str, str]: ...
    @property
    def arrow_data_types(self) -> dict[str, str]: ...
    @property
    def variable_value_labels(self) -> dict[str, dict[float | str, str]]: ...
    @property
    def variable_alignments(self) -> dict[str, str]: ...
    @property
    def variable_storage_widths(self) -> dict[str, int]: ...
    @property
    def variable_display_widths(self) -> dict[str, int]: ...
    @property
    def variable_measures(self) -> dict[str, str]: ...
    @property
    def variable_missing_values(self) -> dict[str, dict]: ...
    @property
    def mr_sets(self) -> dict[str, dict]: ...
    @property
    def variable_roles(self) -> dict[str, str]: ...
    @property
    def variable_attributes(self) -> dict[str, dict[str, list[str]]]: ...
    @property
    def weight_variable(self) -> str | None: ...
    @property
    def schema(self) -> dict: ...

    # Convenience methods
    def label(self, name: str) -> str | None: ...
    def format(self, name: str) -> str | None: ...
    def measure(self, name: str) -> str | None: ...
    def role(self, name: str) -> str | None: ...
    def attribute(self, name: str, attr: str | None = None) -> dict[str, list[str]] | list[str] | None: ...
    def value(self, name: str) -> dict[float | str, str] | None: ...
    def check_var(self, name: str) -> None: ...
    def summary(self) -> None: ...
    def describe(self, names: str | list[str]) -> None: ...
    def diff(
        self, other: SpssMetadata, print_output: bool = True
    ) -> MetaDiff: ...

class MetaDiff:
    @property
    def is_match(self) -> bool: ...
    @property
    def file_level(self) -> dict: ...
    @property
    def variables_only_in_self(self) -> list[str]: ...
    @property
    def variables_only_in_other(self) -> list[str]: ...
    @property
    def variable_labels(self) -> list[dict]: ...
    @property
    def variable_value_labels(self) -> list[dict]: ...
    @property
    def variable_formats(self) -> list[dict]: ...
    @property
    def variable_measures(self) -> list[dict]: ...
    @property
    def variable_display_widths(self) -> list[dict]: ...
    @property
    def variable_storage_widths(self) -> list[dict]: ...
    @property
    def variable_missing_values(self) -> list[dict]: ...
    @property
    def mr_sets(self) -> list[dict]: ...
    @property
    def variable_roles(self) -> list[dict]: ...
    @property
    def variable_attributes(self) -> list[dict]: ...
    def print_summary(self) -> None: ...

def read_sav(
    path: str,
    *,
    columns: list[int] | list[str] | None = None,
    n_rows: int | None = None,
    row_index_name: str | None = None,
    row_index_offset: int = 0,
) -> tuple[polars.DataFrame, SpssMetadata]: ...
def read_sav_metadata(path: str) -> SpssMetadata: ...
def scan_sav(
    path: str,
    *,
    columns: list[int] | list[str] | None = None,
    n_rows: int | None = None,
    row_index_name: str | None = None,
    row_index_offset: int = 0,
) -> tuple[polars.LazyFrame, SpssMetadata]: ...
def write_sav(
    df: polars.DataFrame,
    path: str | Path,
    *,
    meta: SpssMetadata | None = None,
    compress: bool = True,
) -> None: ...
